### ISSUE TITLE
Used on Unix with Python@3.10 and requirements installed

### ISSUE THREAD

**Issue by HellGateAI** [Shakedash-dev/GmailOSINT#1]
It throws that ERROR:

Traceback (most recent call last):
  File "/Users/0x01/Tools/Osint/GmailOSINT/GmailOSINT.py", line 229, in <module>
    main()
  File "/Users/0x01/Tools/Osint/GmailOSINT/GmailOSINT.py", line 153, in main
    driver = uc.Chrome(use_subprocess=True)
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 411, in __init__
    browser = subprocess.Popen(
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1722, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Any Idea why that happend??

Greetz

**Comment by Shakedash-dev** [comment]
I've tested it only on Windows but it should work on any os that as well.
Try "pip install -U undetected-chromedriver"
