### ISSUE TITLE
Failed to getting information

### ISSUE THREAD

**Issue by ImJoke** [Shakedash-dev/GmailOSINT#2]
PS C:\Users\***\Downloads> python -u "c:\Users\***\Downloads\GmailOSINT.py" ****@gmail.com --sleep 20
Poor internet connection...
Please use --sleep 20 (or higher)
Exception ignored in: <function Chrome.__del__ at 0x00000176A0957100>
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 793, in __del__
    self.quit()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 748, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid

**Comment by Shakedash-dev** [comment]
Sometimes the pip exetuable and the python executable are beeing run for different python versions.
Try running pip -V and python -V.
If the versions are the same, you can try "pip install -U undetected-chromedriver"
